{{- if .Values.migrations.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pipery-deploy-bot.fullname" . }}-migrations
  labels:
    {{- include "pipery-deploy-bot.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-1"
    helm.sh/hook-delete-policy: before-hook-creation
data:
  001_init.sql: |
{{ .Files.Get "files/migrations/001_init.sql" | indent 4 }}
{{- end }}
